Fix Unsupported message for dismiss(thenSend) message
guidomb/PortalApplication pull request #2
Opened 2017-04-26 16:19 UTC by jcaracciolo

When a dismiss(thenSend) was being send, the route was not being manage, resulting in an Error State.

2017-04-26 18:46 UTC, guidomb requested changes

2017-04-26 18:46 UTC, guidomb commented on PortalApplication/ApplicationRunner.swift
> +        case (.dismissNavigator(let thenSend), .some(let navigationState)):
rename that parameter to `maybeAction`

2017-04-26 18:46 UTC, guidomb commented on PortalApplication/ApplicationRunner.swift
> +                            switch (thenSend) {
Replace this switch with `maybeAction |> { self.dispatch(action: $0) }`

2017-04-28 11:29 UTC, jcaracciolo commented on PortalApplication/ApplicationRunner.swift
> +                            switch (thenSend) {
|> operator is defined in PortalView, not PortalApplication, should i define it?

2017-04-28 13:06 UTC, guidomb requested changes

2017-04-28 13:06 UTC, guidomb commented on PortalApplication/ApplicationRunner.swift
> +                            switch (thenSend) {
THat's true. Do this instead then.

```swift
if let action = maybeAction {
  self.dispatch(action: action)
}
```

2017-04-28 16:59 UTC, guidomb approved these changes

2017-04-28 16:59 UTC, merged