Pull down to refresh
guidomb/PortalApplication pull request #29
Opened 2017-09-05 17:38 UTC by cristianames92

This PR adds the pull down to refresh feature to the Table component and Collection components, such as Collection and Carousel. 

## Screencast ##
![something](https://user-images.githubusercontent.com/17987418/30074383-bf43e266-9247-11e7-8d4a-9d93be44750f.gif)

2017-09-06 15:09 UTC, cristianames92 commented
For some reason one test is not passing in Bitrise, but in XCode all of them pass, even the UITests (Manually triggered)

2017-09-07 14:41 UTC, guidomb requested changes

2017-09-07 14:41 UTC, guidomb commented on Portal/View/RefreshControl.swift
> +class RefreshController<MessageType> {
~~This should not be here because is `UIKit` dependant. It should be inside the renderers folders in a file called `RefreshControlRenderer`~~

2017-09-07 14:41 UTC, guidomb commented on Portal/View/UIKit/PortalCollectionView.swift
> +    fileprivate var refreshable: RefreshController<ActionType>? = .none
This does not seem to be necessary. The reference graphs seems to be

```
UIScrollView -> UIRefreshControl -> RefreshController
```

2017-09-07 14:41 UTC, guidomb commented on Portal/View/UIKit/PortalCollectionView.swift
> +    public func configRefresh(properties: RefreshProperties<ActionType>, tintColor: Color) {
I would extract this into an extension in `PullToRefreshable` protocol. Also I don't think `RefreshController` is necessary you can do all the configuration in the following method and use a `MessageDispatcher` to send the required message when the user pulls to refresh.

```swift
internal protocol PullToRefreshable {

    associatedtype MessageType

    var scrollView: UIScrollView { get }

    var mailbox: Mailbox<MessageType>

    func configure(pullToRefresh properties: RefreshProperties<ActionType>, tintColor: Color)

}

extension PullToRefreshable where Self == UIScrollView {

    var scrollView: UIScrollView { 
        return self 
    } 

}

extension PullToRefreshable {

    func configure(pullToRefresh properties: RefreshProperties<ActionType>, tintColor: Color) {
        let refreshControl = UIRefreshControl()
        refreshControl.tintColor = tintColor.asUIColor
        refreshControl.attributedTitle = properties.title
        
        switch properties.state {
            
        case .searching:
            scrollView.contentOffset = CGPoint(x:0, y: -refreshControl.frame.size.height)
            refreshControl.beginRefreshing()
            
        case .idle(let message):
            let dispatcher = MessageDispatcher(mailbox: mailbox, message: message)
            self.register(dispatcher: dispatcher)
            refreshControl.dispatch(message: message, for: .valueChanged, with: mailbox) }

        }

        scrollView.refreshControl = refreshControl
    }

}
```

2017-09-07 14:41 UTC, guidomb commented on Portal/View/UIKit/PortalCollectionView.swift
> +    public var refreshMessage: ActionType? = .none
I don't think is necessary. See my comments bellow

2017-09-07 14:41 UTC, guidomb commented on Portal/View/UIKit/PortalTableView.swift
> +    fileprivate var refreshable: RefreshController<ActionType>? = .none
See my comments in `PortalCollectionView`

2017-09-07 14:41 UTC, guidomb commented on Portal/View/RefreshControl.swift
> +class RefreshController<MessageType> {
`RefreshController` should not be necessary, check my comments bellow in `PortalCollectionView`

2017-09-12 21:49 UTC, guidomb approved these changes

2017-09-12 21:58 UTC, merged