Updated Segmented to implement AutoPropertyDiffable
guidomb/PortalApplication pull request #30
Opened 2017-09-05 19:51 UTC by aducret

## Screencast
![pr](https://user-images.githubusercontent.com/1799612/30080574-6a0886a4-925a-11e7-98d8-b913b441710b.gif)

2017-09-05 19:51 UTC, aducret commented
Check PR base before merge!

2017-09-06 12:58 UTC, guidomb requested changes

2017-09-06 12:58 UTC, guidomb commented on Example/Views/Examples/SegmentedScreen.swift
> +    static func view(selected: UInt) -> View {
I would add a parameter name

```swift
static func view(selected index: UInt) -> View {
```

2017-09-06 12:58 UTC, guidomb commented on Example/Views/Examples/SegmentedScreen.swift
> +        let segments = ZipList(left: left, center: center!, right: right)
I think that by adding the following failable initiaiizer to `ZipList` this function (and future uses of `ZipList` like this) would be much cleaner to read

```swift
init?(of collection: Collection<Element>, selected index: UInt) {
  guard index < collection.count else { return nil }

  self.left = collection[0...index - 1]
  self.center = collection[index]
  self.right = collection[(index + 1)...(collection.endIndex - 1)]
}
```

```swift
func createSegmentedComponent(selected index: UInt) -> Component<String> {
  guard let segments = ZipList(from: (0...5), selected: index) else { return container() }

   return segmented(
     segments:  segments,
     style: segmentedStyleSheet { base, segmented in
        base.backgroundColor = .white
        segmented.textFont = Font(name: "Helvetica")
        segmented.textSize = 20
        segmented.textColor = .red
        segmented.borderColor = .green
      }
  ) 
}

func view(selected index: UInt) -> View {
  return View(
    navigator: .main,
    root: .stack(ExampleApplication.navigationBar(title: "Segmented")),
    component: container(
      children: [createSegmentedComponent(selected: index)],
       style: styleSheet {
         $0.backgroundColor = .black
       },
       layout: layout {
         $0.flex = flex() { $0.grow = .one }
       }
     )
)
```

2017-09-07 13:26 UTC, guidomb approved these changes

2017-09-07 14:22 UTC, merged